// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrlqwyfdD4sRLoUO-NEWCvRQmWNpuP75c',
    appId: '1:356456247138:web:835d684d7e71f0775cc63b',
    messagingSenderId: '356456247138',
    projectId: 'musix-6fc50',
    authDomain: 'musix-6fc50.firebaseapp.com',
    storageBucket: 'musix-6fc50.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1MxbGhtmMjNPsCdqupKtGdJEnuDVq90',
    appId: '1:356456247138:android:2057160bdabc389a5cc63b',
    messagingSenderId: '356456247138',
    projectId: 'musix-6fc50',
    storageBucket: 'musix-6fc50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD0KY8VwhDhzJOhm3Des1haa_NlG5ofMU',
    appId: '1:356456247138:ios:aa5606f32452c9e45cc63b',
    messagingSenderId: '356456247138',
    projectId: 'musix-6fc50',
    storageBucket: 'musix-6fc50.firebasestorage.app',
    iosBundleId: 'com.sachicodex.musix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD0KY8VwhDhzJOhm3Des1haa_NlG5ofMU',
    appId: '1:356456247138:ios:aa5606f32452c9e45cc63b',
    messagingSenderId: '356456247138',
    projectId: 'musix-6fc50',
    storageBucket: 'musix-6fc50.firebasestorage.app',
    iosBundleId: 'com.sachicodex.musix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrlqwyfdD4sRLoUO-NEWCvRQmWNpuP75c',
    appId: '1:356456247138:web:0056f4601e4306985cc63b',
    messagingSenderId: '356456247138',
    projectId: 'musix-6fc50',
    authDomain: 'musix-6fc50.firebaseapp.com',
    storageBucket: 'musix-6fc50.firebasestorage.app',
  );
}
